"use client";
import { useMemo,useState } from "react";
import { useRouter,useSearchParams } from "next/navigation";
import { money } from "@/lib/utils";

type Color={id:string;name:string;hex:string|null};
type Gift={id:string;name:string;description:string|null;imageUrl:string|null;approximateValue:any;desiredQuantity:number;reservedQuantity:number;priority:string;purchaseUrl:string|null;brand:string|null;model:string|null;note:string|null;acceptsInstallments:boolean;installmentCount:number|null;installmentValue:any;installments:{status:string}[];category:{id:string;name:string;slug:string;icon:string|null};colors:{color:Color}[]};
export function GiftList({gifts,categories,colors}:{gifts:Gift[];categories:{id:string;name:string;slug:string}[];colors:Color[]}){
 const sp=useSearchParams(); const router=useRouter();
 const initial=sp.get("reservar"); const [reserveId,setReserveId]=useState(initial);
 const [query,setQuery]=useState(""); const [cat,setCat]=useState("all"); const [availability,setAvailability]=useState("all"); const [priority,setPriority]=useState("all"); const [color,setColor]=useState("all"); const [price,setPrice]=useState("all");
 const [form,setForm]=useState({name:"",phone:"",message:"",confirm:false}); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [success,setSuccess]=useState<{token:string;gift:Gift}|null>(null);
 const selected=gifts.find(g=>g.id===reserveId)||null;
 const filtered=useMemo(()=>gifts.filter(g=>{const val=g.approximateValue==null?null:Number(g.approximateValue);const rem=g.acceptsInstallments?g.installments.filter(i=>i.status==="AVAILABLE").length:g.desiredQuantity-g.reservedQuantity;if(query&&!g.name.toLowerCase().includes(query.toLowerCase()))return false;if(cat!=="all"&&g.category.slug!==cat)return false;if(availability==="available"&&rem<=0)return false;if(priority!=="all"&&g.priority!==priority)return false;if(color!=="all"&&!g.colors.some(x=>x.color.id===color))return false;if(price==="none"&&val!==null)return false;if(price==="0-50"&&!(val!==null&&val<=50))return false;if(price==="50-100"&&!(val!==null&&val>50&&val<=100))return false;if(price==="100-200"&&!(val!==null&&val>100&&val<=200))return false;if(price==="200-400"&&!(val!==null&&val>200&&val<=400))return false;if(price==="400+"&&!(val!==null&&val>400))return false;return true}).sort((a,b)=>{const pa=(x:Gift)=>x.priority==="HIGH"?0:x.priority==="NORMAL"?1:2;return pa(a)-pa(b)}),[gifts,query,cat,availability,priority,color,price]);
 function open(id:string){setReserveId(id);setSuccess(null);setError("");router.replace(`/presentes?reservar=${id}`,{scroll:false})}
 function close(){setReserveId(null);setSuccess(null);setError("");router.replace("/presentes",{scroll:false})}
 async function submit(e:React.FormEvent){e.preventDefault();if(!selected)return;setBusy(true);setError("");const r=await fetch("/api/reservations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({giftId:selected.id,...form})});const j=await r.json();setBusy(false);if(!r.ok){setError(j.error||"Não foi possível reservar.");return}setSuccess({token:j.token,gift:selected});}
 return <>
  <div className="pill-tabs">{[{slug:"all",name:"Todos"},...categories].map(c=><button key={c.slug} className={`btn ${cat===c.slug?"btn-primary":"btn-soft"}`} onClick={()=>setCat(c.slug)}>{c.name}</button>)}</div>
  <div className="filters"><div style={{flex:"2 1 220px"}}><input className="input" placeholder="Buscar presente" value={query} onChange={e=>setQuery(e.target.value)}/></div><select className="select" style={{flex:"1 1 160px"}} value={availability} onChange={e=>setAvailability(e.target.value)}><option value="all">Disponíveis e escolhidos</option><option value="available">Somente disponíveis</option></select><select className="select" style={{flex:"1 1 150px"}} value={price} onChange={e=>setPrice(e.target.value)}><option value="all">Qualquer valor</option><option value="none">Sem valor informado</option><option value="0-50">Até R$ 50</option><option value="50-100">R$ 50 a R$ 100</option><option value="100-200">R$ 100 a R$ 200</option><option value="200-400">R$ 200 a R$ 400</option><option value="400+">Acima de R$ 400</option></select><select className="select" style={{flex:"1 1 150px"}} value={priority} onChange={e=>setPriority(e.target.value)}><option value="all">Todas prioridades</option><option value="HIGH">Prioridade alta</option><option value="NORMAL">Prioridade normal</option><option value="OPTIONAL">Opcionais</option></select><select className="select" style={{flex:"1 1 150px"}} value={color} onChange={e=>setColor(e.target.value)}><option value="all">Todas as cores</option>{colors.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div>
  {filtered.length?<div className="grid grid-3">{filtered.map(g=>{const rem=g.acceptsInstallments?g.installments.filter(i=>i.status==="AVAILABLE").length:g.desiredQuantity-g.reservedQuantity;return <article key={g.id} className="card gift-card"><div className="gift-img">{g.imageUrl?<img src={g.imageUrl} alt={g.name}/>:<span aria-hidden>{g.category.icon||"🎁"}</span>}</div><div className="gift-body"><div style={{display:"flex",gap:8,justifyContent:"space-between"}}><span className="badge">{g.category.name}</span></div><div className="gift-name">{g.name}</div>{g.description&&<p className="muted" style={{margin:0}}>{g.description}</p>}{g.approximateValue!=null&&<div><strong>{money(g.approximateValue)}</strong> <span className="muted" style={{fontSize:12}}>aprox.</span></div>}{g.acceptsInstallments&&<div className="notice"><strong>{rem}</strong> de {g.installmentCount} cotas disponíveis{g.installmentValue!=null?` · ${money(g.installmentValue)} cada`:""}</div>}{g.colors.length>0&&<div><div className="muted" style={{fontSize:12}}>Cores preferidas</div><div className="color-row">{g.colors.map(x=><span key={x.color.id} title={x.color.name} className="dot" style={{background:x.color.hex||"linear-gradient(45deg,#ddd,#fff)"}}/>)}</div></div>}<div className={rem>0?"status-ok":"status-out"}>{rem<=0?"Já escolhido 💛":g.acceptsInstallments?`${rem} cotas disponíveis`:g.desiredQuantity>1?`${g.reservedQuantity} de ${g.desiredQuantity} escolhidos · faltam ${rem}`:"Disponível"}</div>{g.brand&&<div className="muted" style={{fontSize:13}}>Sugestão: {g.brand}{g.model?` · ${g.model}`:""} ou similar</div>}<div style={{marginTop:"auto"}}><button className="btn btn-primary" style={{width:"100%"}} disabled={rem<=0} onClick={()=>open(g.id)}>{rem>0?"Quero dar este presente":"Indisponível"}</button></div></div></article>})}</div>:<div className="card empty">Nenhum presente corresponde aos filtros.</div>}
  {selected&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal">{success?<div><div className="eyebrow">Reserva concluída</div><h2 className="subtitle">Presente reservado! 🎁</h2><p>Obrigado, {form.name}. Pedro e Larissa vão ficar muito felizes com seu carinho.</p><div className="notice"><strong>{success.gift.name}</strong></div><p className="muted">Guarde seu link pessoal. É por ele que você poderá cancelar a reserva ou alterar sua mensagem.</p><div className="form">{success.gift.purchaseUrl&&<a target="_blank" className="btn btn-primary" href={success.gift.purchaseUrl}>Ver sugestão de compra</a>}<button className="btn" onClick={()=>navigator.clipboard.writeText(`${location.origin}/minha-reserva/${success.token}`).then(()=>alert("Link copiado!"))}>Guardar meu link da reserva</button><a className="btn" href={`/minha-reserva/${success.token}`}>Abrir minha reserva</a><button className="btn btn-soft" onClick={close}>Escolher outro presente</button></div>{success.gift.purchaseUrl&&<p className="muted" style={{fontSize:13}}>O link é apenas uma sugestão. Você pode comprar onde preferir.</p>}</div>:<><button aria-label="Fechar" onClick={close} style={{float:"right",border:0,background:"transparent",fontSize:24}}>×</button><div className="eyebrow">Escolha do presente</div><h2 className="subtitle">{selected.name}</h2>{selected.approximateValue!=null&&<p><strong>{money(selected.approximateValue)}</strong> <span className="muted">aprox.</span></p>}<form className="form" onSubmit={submit}><div className="field"><label>Nome *</label><input className="input" required minLength={2} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="field"><label>WhatsApp ou telefone *</label><input className="input" required inputMode="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div className="field"><label>Mensagem para Pedro & Larissa</label><textarea className="textarea" value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></div><label className="checkline"><input type="checkbox" required checked={form.confirm} onChange={e=>setForm({...form,confirm:e.target.checked})}/><span>Confirmo que desejo reservar este item. Se eu não puder comprá-lo depois, usarei meu link pessoal para cancelar a reserva.</span></label>{error&&<div className="notice error">{error}</div>}<button className="btn btn-primary" disabled={busy}>{busy?"Confirmando...":"Confirmar presente 🎁"}</button></form>{selected.purchaseUrl&&<p className="muted" style={{fontSize:13}}>O link é apenas uma sugestão. Você pode comprar onde preferir.</p>}</>}</div></div>}
 </>
}
